---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/2/28 下午4:57
---
a = 5
local b = 5
function joke()
    c = 5
    local d = 6
end
joke()
print(c, d)

do
    local a = 6
    b = 6
    print(a, b)
end

print(a, b)

t = { n = 1 }
a = "hello" .. "world"
t.n = t.n + 1
print(a .. t.n)

x = 1
a, b = 10, 2 * x

print(a .. b)

print("---------- x,y swap")
x, y = 1, 2
print(x, y)
x, y = y, x
print(x, y)

a = { i = "1", j = "2" }

print("a[i]:" .. a.i .. ",a[j]" .. a.j)
a.i, a.j = a.j, a.i
print("a[i]:" .. a.i .. ",a[j]" .. a.j)

a,b,c =0,1
print(a,b,c)

a,b=a+1,b+1,b+2
print(a,b)

a,b,c=0
print(a,b,c)

a,b,c = 0,0,0
print(a,b,c)

function f()
    return {"123","666"}
end

a,b = f()
print(a,b)

test = {test1="fdsa",test="fdsaa"}
print(test["test1"],test["test"])
print(test[1],test[2])
