---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/3/1 上午7:14
---
if (0)
then
    print("数字 0 为 true")
end

a = 10

if (a < 20)
then
    print("a小于20")
end
print("a 的值为:",a)