---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/3/1 上午7:16
---
a = 100;
if (a < 20)
then
    print("a小于20")
else
    print("a大于20")
end
print("a 的值为:", a)

a = 100

--
if (a == 10)
then
    print("a 的值为: 10")
elseif (a == 20) then
    print("a 的值为: 20")
elseif (a == 30) then
    print("a 的值为:30")
else
    print("没有匹配的a的值")
end
print("a 的真实值为:",a)
