---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/3/1 上午7:20
---
a = 100
b = 200
if (a == 100)
then
    if (b == 200)
    then
        print("a 的值为: 100 b 的值为200")
    end
end
print("a 的值为:",a)
print("a 的值为:",b)