---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/3/1 上午7:26
---
myprint = function(param)
    print("这是打印函数 -  ##", param, "##")
end

function add(num1, num2, functionPrint)
    result = num1 + num2
    functionPrint(result)
end

myprint(10)
add(2, 5, myprint)

--多返回值
s, e = string.find("www.runoob.com", "runoob")
print(s, e)

-- 返回列表
function maximum(a)
    local mi = 1
    local m = a[mi]
    for i, val in ipairs(a) do
        if (val > m) then
            mi = i
            m = val
        end
    end
    return m, mi
end

print(maximum({8,10,23,12,5}))
