---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/2/28 下午11:07
---
a = 10

while (a < 20)
do
    print("a 的值为：", a)
    a = a + 1
    if (a > 15)
    then
        break
    end
end

