---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/2/28 下午10:57
---
j = 2
for i = 2, 10 do
    for j = 2, (i / j), 2 do
        if (not (i % j))
        then
            break
        end
        if (j > (i / j))
        then
            print("i的值为:", i)
        end
    end
end