---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/2/28 下午11:11
---
for i = 1, 3 do
    if i <=2 then
        print(i,"yes continue")
        goto continue
    end
    print(i," no continue")
    ::continue::
    print([[i'm end]])
end