---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/2/28 下午11:10
---
i = 0
:: s1 ::
do
    print(i)
    i = i + 1
end

if i > 3 then
    os.exit()
end

goto s1