---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/2/28 下午11:08
---
local a = 1
:: label ::
print("--- goto label ----", a)

a = a + 1
if a < 3 then
    goto label
end