---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/3/2 上午7:14
---
fruits = {"banana",kwy="zz","orange","apple"}

-- 在末尾输入
table.insert(fruits,"mango")
print("索引为4 的元素为",fruits[4])

-- 在索引为2 的建处输入
table.insert(fruits,2,"grapes")
print("索引为2 的元素为",fruits[2])

print("最后一个元素为",fruits[5])
table.remove(fruits)
print("移除最后一个元素为",fruits[5])

for i, v in pairs(fruits) do

    print(i,v)
end