---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/3/2 上午7:21
---
fruits = { "banana",key="zz",f="gg", "orange", "apple", "grapes" }
print("排序前")
table.sort(fruits)
for i, v in pairs(fruits) do
    print(i,v)
end

table.sort(fruits)
print("排序后")
for i, v in pairs(fruits) do
    print(i,v)
end
