---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/3/2 上午7:37
---
function table_maxn(t)
    local mn = nil
    for i, v in pairs(t) do
        print(i,v)
        if (mn == nil) then
            mn = v
        end
        if (mn < v) then
            mn = v
        end
    end
    return mn
end

function table_leng(t)
    local length = 0
    for i, v in pairs(t) do
        length = length+1
    end
    return length;
end

tbl = {[1] = 2, [2] = 6,[3] =34,[26]=5}
tbl2 = {2,6,34,5}
print("tbl 最大值",table_maxn(tbl))
print("tbl 长度",table_leng(tbl))
