---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/2/28 下午4:51
---
function testFun(tab, fun)
    for k, v in pairs(tab) do
        print(fun(k,v))
    end
end

tab = {key1="val1",key2="val2"};

testFun(tab,function(key,val)
    return key .. "=".. val;
end);