---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/2/28 上午9:54
---
print(type("Hello World")) --> string
print(type(10.4 * 3))  --> number
print(type(print)) --> function
print(type(type)) --> function
print(type(true)) --> boolean
print(type(nil)) --> nil
print(type(type(x))) --> string
print(type(X))