---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/2/28 上午10:54
---
print(2)
print(2.2)
print(0.2)
print(2e+1)
print(0.2e-1)
print(7.8263692594256 * 2)
print(7.8263692594256e-06 * 2)
