---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/2/28 下午4:36
---
html = [[
<html>
    <head></head>
    <body>
        <a href = "http://www.runoob.com">菜鸟编程</a>
    </body>
</html>
]]
print(html)

print("2" + 6)


print("2" + "6")

print("2+6")

print("-2e2" * "6")

-- 连接使用..
print("a" .. 'b')
print(157 .. 428)

-- 使用#计算字符串的长度
len = "www.runoob.com"
print(#len)
print(#"www.runoob.com")
print("error" + 1)

