---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/2/28 下午4:46
---
local tabl1 = {}

local tabol2 = { "apple", "pear", "orange", "grape" }

for i, v in pairs(tabol2) do
    print("key",i)
end
