---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lh.
--- DateTime: 2021/2/28 上午10:15
---
tab1 = {key1 = "val1", key2 = "val2","val3","val4"}
for k , v in pairs(tab1) do
    print(k .. " _ " .. v)
end
print("-------")
tab1.key1 = nil
for k, v in pairs(tab1) do
    print(k .. " _ " .. v)
end
print("-------")
va3="wer"
tab2 = {"val","va2",va3}
for k , v in pairs(tab2) do
    print(k .. " _ " .. v)
    end
